#       Sgourakis Lab
#   Author: Sagar Gupta
#   Date: November 29, 2022
#   Email: sagarg@sas.upenn.edu

'''
Important constant values used throughout RepPred
'''

REP_PRED_DIR = "."
ROSETTA_DIR = "/Users/titanium/Downloads/rosetta/"
A0201_HLA_SEQUENCE = "GSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHRVDLGTLRGYYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAAHVAEQLRAYLEGTCVEWLRRYLENGKETLQ"
MHC_CHAIN = "A"
PEP_CHAIN = "B"

