#       Sgourakis Lab
#   Author: Sagar Gupta
#   Date: November 29, 2022
#   Email: sagarg@sas.upenn.edu

'''
Important constant values used throughout RepPred
'''

REP_PRED_DIR = "."
ROSETTA_DIR = "/scr1/users/guptas10/amain/rosetta_copy/"
A0201_HLA_SEQUENCE = "GSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHRVDLGTLRGYYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAAHVAEQLRAYLEGTCVEWLRRYLENGKETLQ"
MHC_CHAIN = "A"
PEP_CHAIN = "B"

